ProyectoFinalCarritoCompra/Controllers/CarritoController.cs
using Microsoft.AspNet.Identity;
using ProyectoFinalCarritoCompra.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace ProyectoFinalCarritoCompra.Controllers
{
    public class CarritoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Carrito
        public ActionResult Index()
        {
            if (HttpContext.Session["ListaCarrito"] == null)
            {
                List<CarritoView> IdProductos = new List<CarritoView>();
                HttpContext.Session["ListaCarrito"] = IdProductos;
            }
            if (HttpContext.Session["IdProductos"] != null)
            {
                List<int> lista = (List<int>)HttpContext.Session["IdProductos"];
                List<CarritoView> Actualista = (List<CarritoView>)HttpContext.Session["ListaCarrito"];
                CarritoView valida = new CarritoView();
                foreach (int item in lista)
                {
                    valida = Actualista.Where(p => p.IdProducto == item).FirstOrDefault();
                    if ( valida == null)
                    {
                        Producto prod = db.Producto.Find(item);
                        CarritoView productsView = new CarritoView();
                        productsView.NombreProducto = prod.Nombre;
                        productsView.ImgenProducto = prod.Imagen;
                        productsView.Precio = prod.Precio;
                        productsView.Cantidad = 1;
                        productsView.IdProducto = prod.Id;
                        Actualista.Add(productsView);
                    }
                    
                }
                HttpContext.Session["ListaCarrito"] = Actualista;
            }
            return View();
        }

        // GET: Carrito/Details/5
        public async Task<ActionResult> SumarCantidad(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<CarritoView> Actualista = (List<CarritoView>)HttpContext.Session["ListaCarrito"];
            CarritoView item = Actualista.Where(i => i.IdProducto == id).FirstOrDefault();
            Producto producto = db.Producto.Find(item.IdProducto);
            var indice = Actualista.IndexOf(item);
            if (item.Cantidad < producto.Stock)
            {
                item.Cantidad = item.Cantidad+1;
                Actualista.RemoveAt(indice);
                Actualista.Insert(indice, item);
                HttpContext.Session["ListaCarrito"] = Actualista;
            }
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> RestarCantidad(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<CarritoView> Actualista = (List<CarritoView>)HttpContext.Session["ListaCarrito"];
            CarritoView item = Actualista.Where(i => i.IdProducto == id).FirstOrDefault();
            var indice = Actualista.IndexOf(item);
            if (item.Cantidad > 1)
            {
                item.Cantidad = item.Cantidad - 1;
                Actualista.RemoveAt(indice);
                Actualista.Insert(indice, item);
                HttpContext.Session["ListaCarrito"] = Actualista;
            }
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> EliminarProducto(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<CarritoView> Actualista = (List<CarritoView>)HttpContext.Session["ListaCarrito"];
            List<int> lista = (List<int>)HttpContext.Session["IdProductos"];
            CarritoView item = Actualista.Where(i => i.IdProducto == id).FirstOrDefault();
            var indice = Actualista.IndexOf(item);
            lista.RemoveAt(indice);
            Actualista.RemoveAt(indice);
            HttpContext.Session["ListaCarrito"] = Actualista;
            HttpContext.Session["IdProductos"] = lista;
            return RedirectToAction("Index");
        }

        // GET: Carrito/
        public async Task<ActionResult> PostCompra()
        {
            Random rnd = new Random();
            int folio = rnd.Next(1, 10000000);
            List<Compra> listaPost = new List<Compra>();
            List<CarritoView> Actualista = (List<CarritoView>)HttpContext.Session["ListaCarrito"];
            List<int> lista = (List<int>)HttpContext.Session["IdProductos"];
            foreach (CarritoView item in Actualista)
            {
                Compra compra = new Compra()
                {
                    Id = 1,
                    Nombre = item.NombreProducto,
                    Cantidad = item.Cantidad,
                    Precio = item.Precio,
                    Fecha_Compra = DateTime.Now,
                    idUsuario = User.Identity.GetUserId(),
                    Folio = folio
                };
                Producto prod = db.Producto.Where(x => x.Id == item.IdProducto).FirstOrDefault();
                prod.Stock = prod.Stock - item.Cantidad;
                db.Entry(prod).State = EntityState.Modified;
                db.Compra.Add(compra);
                db.SaveChanges();
                listaPost.Add(compra);

            }
            lista.Clear();
            Actualista.Clear();
            HttpContext.Session["ListaCarrito"] = Actualista;
            HttpContext.Session["IdProductos"] = lista;
            HttpContext.Session["ListaPostComp"] = listaPost;
            return View();
        }
    }
}

ProyectoFinalCarritoCompra/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinalCarritoCompra.Models;

namespace ProyectoFinalCarritoCompra.Controllers
{
    public class MarcaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Marca
        public async Task<ActionResult> Index()
        {
            return View(await db.Marca.ToListAsync());
        }

        // GET: Marca/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marca marca = await db.Marca.FindAsync(id);
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // GET: Marca/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Marca/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,NombreMarca")] Marca marca)
        {
            if (ModelState.IsValid)
            {
                db.Marca.Add(marca);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(marca);
        }

        // GET: Marca/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marca marca = await db.Marca.FindAsync(id);
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // POST: Marca/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,NombreMarca")] Marca marca)
        {
            if (ModelState.IsValid)
            {
                db.Entry(marca).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(marca);
        }

        // GET: Marca/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marca marca = await db.Marca.FindAsync(id);
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // POST: Marca/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Marca marca = await db.Marca.FindAsync(id);
            db.Marca.Remove(marca);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinalCarritoCompra/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinalCarritoCompra.Models;

namespace ProyectoFinalCarritoCompra.Controllers
{
    public class ProductoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Producto
        public async Task<ActionResult> Index()
        {
            var producto = db.Producto.Include(p => p.Categoria).Include(p => p.Marca);
            return View(await producto.ToListAsync());
        }

        // GET: Producto/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = await db.Producto.FindAsync(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }
        public async Task<ActionResult> DetalleProducto(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = await db.Producto.FindAsync(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Producto/Create
        public ActionResult Create()
        {
            ViewBag.idCategoria = new SelectList(db.Categoria, "Id", "NombreCat");
            ViewBag.idMarca = new SelectList(db.Marca, "Id", "NombreMarca");
            return View();
        }

        // POST: Producto/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CodBarra,Nombre,Descripcion,Stock,Precio,Imagen,idMarca,idCategoria")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Producto.Add(producto);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.idCategoria = new SelectList(db.Categoria, "Id", "NombreCat", producto.idCategoria);
            ViewBag.idMarca = new SelectList(db.Marca, "Id", "NombreMarca", producto.idMarca);
            return View(producto);
        }

        // GET: Producto/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = await db.Producto.FindAsync(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCategoria = new SelectList(db.Categoria, "Id", "NombreCat", producto.idCategoria);
            ViewBag.idMarca = new SelectList(db.Marca, "Id", "NombreMarca", producto.idMarca);
            return View(producto);
        }

        // POST: Producto/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CodBarra,Nombre,Descripcion,Stock,Precio,Imagen,idMarca,idCategoria")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idCategoria = new SelectList(db.Categoria, "Id", "NombreCat", producto.idCategoria);
            ViewBag.idMarca = new SelectList(db.Marca, "Id", "NombreMarca", producto.idMarca);
            return View(producto);
        }

        // GET: Producto/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = await db.Producto.FindAsync(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Producto producto = await db.Producto.FindAsync(id);
            db.Producto.Remove(producto);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinalCarritoCompra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    @Styles.Render("~/Content/styles.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                <img src="@Url.Content("~/Content/imgs/stdigital.png")" alt="StDigital logo" />
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Productos", "Productos", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (User.IsInRole("Administrador"))
                    {
                        <li>@Html.ActionLink("Mantenedores", "Mantenedores", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>
                @{List<int> list = Session["IdProductos"] as List<int>;
                    if (list != null)
                    {
                        if (list.Count() >= 1)
                        {
                            <ul class="navbar-nav navbar-right">
                                <a href="@Url.Action("Index", "Carrito")" class="navbar-brand">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                    </svg>
                                    <span class="badge bg-red fg-white">@list.Count()</span>
                                </a>
                            </ul>
                        }
                    }
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>

    <div class="container-fluid bg-dark mt-4">
        <div class="container">
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-5 ">
                <div class="col-md-4 d-flex align-items-center">
                    <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
                    </a>
                    <span class="mb-3 mb-md-0 text-body-secondary text-white">Derechos Reservados&copy; ST Digital 2023</span>
                </div>
                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3">
                        <a class="text-white" href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="white" class="bi bi-facebook" viewBox="0 0 16 16">
                                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                            </svg>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-body-secondary" href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="white" class="bi bi-instagram" viewBox="0 0 16 16">
                                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
                            </svg>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-body-secondary" href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="white" class="bi bi-twitter" viewBox="0 0 16 16">
                                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
                            </svg>
                        </a>
                    </li>
                </ul>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProyectoFinalCarritoCompra/Views/Shared/_MantenedoresPartial.cshtml
<div class="col-2 bg-dark">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
        
        <h4 class="mt-4">Mantenedores</h4>
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
            <li class="nav-item">
                <a href="@Url.Action("Mantenedores", "Home")" class="nav-link align-middle px-0">
                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Inicio</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Producto")" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Productos</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Categoria")" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Categorias</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Marca")" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Marcas</span>
                </a>
            </li>
        </ul>

    </div>
</div>